/* options_internals.h: options dialog boxes
   Copyright (c) 2001-2002,2004 Philip Kendall

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

   Author contact information:

   E-mail: philip-fuse@shadowmagic.org.uk

*/

/* This file is autogenerated from options.dat by options-header.pl.
   Do not edit unless you know what you're doing! */

#ifndef FUSE_WIDGETOPTIONS_INTERNALS_H
#define FUSE_WIDGETOPTIONS_INTERNALS_H

#ifndef FUSE_SETTINGS_H
#include "settings.h"
#endif

#ifndef FUSE_WIDGET_H
#include "ui/widget/widget.h"
#endif

extern settings_info widget_options_settings;

int widget_general_draw( void *data );
void widget_general_keyhandler( input_key key );

int widget_media_draw( void *data );
void widget_media_keyhandler( input_key key );

int widget_peripherals_general_draw( void *data );
void widget_peripherals_general_keyhandler( input_key key );

int widget_peripherals_disk_draw( void *data );
void widget_peripherals_disk_keyhandler( input_key key );

int widget_rzx_draw( void *data );
void widget_rzx_keyhandler( input_key key );

int widget_sound_draw( void *data );
void widget_sound_keyhandler( input_key key );

int widget_diskoptions_draw( void *data );
void widget_diskoptions_keyhandler( input_key key );

int widget_movie_draw( void *data );
void widget_movie_keyhandler( input_key key );

#endif				/* #ifndef FUSE_WIDGETOPTIONS_INTERNALS_H */
